INSERT INTO COMPAGNIE (ID, NAME) VALUES (1, 'NAME1');
INSERT INTO COMPAGNIE (ID, NAME) VALUES (2, 'NAME2');
INSERT INTO COMPAGNIE (ID, NAME) VALUES (3, 'NAME3');

INSERT INTO CLIENT (ID, NAME) VALUES (1, 'CLIENT1');
INSERT INTO CLIENT (ID, NAME) VALUES (2, 'CLIENT2');
INSERT INTO CLIENT (ID, NAME) VALUES (3, 'CLIENT3');
INSERT INTO CLIENT (ID, NAME) VALUES (4, 'CLIENT4');
INSERT INTO CLIENT (ID, NAME) VALUES (5, 'CLIENT5');

INSERT INTO VOL (ID, COMPAGNIE_ID,DATE) VALUES (1,2,'2020-12-01');
INSERT INTO VOL (ID, COMPAGNIE_ID,DATE) VALUES (2,2,'2020-12-02');
INSERT INTO VOL (ID, COMPAGNIE_ID,DATE) VALUES (3,3,'2020-12-03');
INSERT INTO VOL (ID, COMPAGNIE_ID,DATE) VALUES (4,1,'2020-12-04');


INSERT INTO VOL_CLIENTS (CLIENTS_ID, VOL_ID) VALUES (1,1);
INSERT INTO VOL_CLIENTS (CLIENTS_ID, VOL_ID) VALUES (2,1);
INSERT INTO VOL_CLIENTS (CLIENTS_ID, VOL_ID) VALUES (3,2);
INSERT INTO VOL_CLIENTS (CLIENTS_ID, VOL_ID) VALUES (3,1);
INSERT INTO VOL_CLIENTS (CLIENTS_ID, VOL_ID) VALUES (4,2);
INSERT INTO VOL_CLIENTS (CLIENTS_ID, VOL_ID) VALUES (5,3);